---
title: "Final Grade Reflection"
author: "Your Name Goes Here"
format: pdf
editor: visual
---

Final Grade Reflection


I think I've earned about a C in the course at the end of it.  When I wrote the Week 6 reflection I was quite morose about the grade I had earned.  While I think I have bounced back and improved my overall effort, as we got further into the course my lack of a background in coding really started to rear its head.  Especially with regular expressions and the 12 days of christmas lab, the continued abstraction of abstraction to create meaning through code started becoming very difficult to keep up with.   

My attendance continued to be stellar, as well as being fully "present" in class.  I have done a better job of turning in coursework, and I have continued to turn in my Tuesday Practice activities with the exception of the 12 days of christmas.  And, just like with my Week 6 reflection, there are still a number of ~60-90% finished labs and challenges that litter my Stats 531 folder (labs 4, 8, 9)

In more specific terms I believe I have achieved a number of Learning Targets. WD-2 has been satisfied by Lab 3 in which I used the select() function many times (Lab 3 Revised, code chunk: "Young Age Familiarity"). WD-4 has been satisfied by lab 3 in which I used the mutate() function to create variables in a dataframe using if_else statements, changing variables into factors, into numeric, etc (Lab 3 Revised, code chunk: "Clean The Data"). WD-5 has been satisfied by Lab 4 in which I used the left_join, anti_join(), and semi_join() functions on various dataframes in order to combine/extract/reshape data depending on the analysis (Lab 4_Avocat, code chunk: "Exercise #7). WD-6 has been satisfied by Lab 3 with the filter() function to find Justin Bieber (Lab 3 Revised, code chunk: "Task: Filtering Bieber").  WD-7 has been satisfied by Lab 4 in which I pivoted dataframes wider and longer (Lab 4_Avocat, code chunks: "Exercise #6", "Exercise #7")

R-1 has been satisfied with Challenge 4 in which I used the here package, logical object names, clear section headers, tidy code, and explanatory text to create a professional looking and reproducible analysis (Lab 4 Challenge, code chunk: "Setup"). R-2 has been satisfied by Challenge 4 in which I took care to write well-documented and tidy code (Lab 4 Challenge, code chunks: all). R-3 has been satisfied by Lab 3 in which I used the select() function to select columns by their variable name instead of their relative position in the dataframe (Lab 3 Revised: code chunk: "Demographics"). 

DVS-1 has been satisfied by Lab 4 in which I created multiple different ggplots analyzing the dataset in many different ways. DVS-2 has been satisfied by Lab 4 in which I changed the width of columns, the color of the data, and implemented geom_jitter to make the visualization clear (Lab 4_Avocat, code chunks: "Exercise #5", "Exercise #6").  DVS-3 was satisfied by Challenge 2 in which I used many optional ggplot functions to change the shape of the graph, the title, and the color of the boxplots (Lab2Challenge, code chunk: "Plotting"). DSV-4 was satisfied by Lab 4 in which I used the summarize() function many times on numerical variables (Lab 4_Avocat, code chunks: "Exercise #5", "Exercise #6"). DSV-5 was satisfied by Lab 4 in which I summarized across multiple variables multiple times in order to distill avocado data into comprehensible data frames (Lab 4_Avocat, code chunks: "Exercise #5", "Exercise #6").

PE-1 was satisfied by Lab 3 in which the code is concise and does not repeat itself, I used mutate() in conjunction with across() in order to condense my code (Lab 3 Revised, code chunk: "Demographics"). PE-2 was satisfied by Lab 3 in the same way (Lab 3 Revised, code chunk: "Demographics"). PE-3 was satisfied by Challenge 2 in which I iteratively added annotations to my ggplot (Lab2Challenge, code chunk: "Task 1"). PE-4 has been satisfied by Lab 3 in which I made great use of functions like: mutate(), group_by(), across(), ggplot, and slice() (Lab 3 Revised, code chunk: "Non-white Women Familiarity").

DSM-2 was satisfied by Lab 9 in which I fit a linear regression of Allans and extracted necessary summary measures (Lab 9, code chunks: "Step 3", "Step 4")

As before, I have had a hard time keeping up with reading all of the material prior to Tuesday's class, though I do try to at the very least watch the videos. I have been better about keeping in contact with my lab-mates as well as completing constructive peer-reviews. .

In summation, I believe I am still not entirely accomplishing what I set out to do in class, though nearer than I was in Week 6. I am still learning R each week, and feel much more accomplished in understanding how to perform data science than I did previously.  I would say my grade is probably either a C or C- at the moment. 