---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

Lab 3 and Lab 4 were very helpful in growing to be a proficient data scientist. In both labs we were tasked with making sense of a large dataset by paring it down to its relevant parts. Some of that required more simple functions in Lab 3, such as filter, select, and group_by in conjunction with summarize. These are simple functions, but vital to target and remove unrelated portions from a dataset. I especially notice my growth at my internship at Caltrans at which I am constantly working on excel spreadsheets and manipulating them by hand; the work computer I use does not have R or Rstudio installed. You need to be able to manipulate and transform datasets with minimal input to be an effective data scientist, especially as the size of the dataset increases, and I often feel hamstrung at my job.

Lab 7 was instrumental in teaching me how to analyze data visually and the importance of custom functions. In order to create multiple similar visualizations with ggplot the data scientist's work is made much simpler with a custom function. Otherwise you are likely to make a mistake when copy/pasting/altering the same code chunk over and over again. By creating a function that can be manipulated to examine the datasets in multiple different ways you can quickly make inferences without worrying about error in your code. I believe I made showed growth in this area through Lab 7 when creating and comparing multiple ggplots through custom functions.
