---
title: "The Power of Efficiency"
format: html
editor: visual
---

To me, efficiency in data science has multiple parts. First and foremost, the code should not repeat itself in a literal way, and operations that can be iterated should be. Custom functions also play a large part in reducing repetition in code. Efficiency in data science looks like concise code that does not needlessly repeat functions so as to improve the code writing as well as the reading. Efficiency allows you to write code more quickly and perform tasks that would otherwise be impossible by how long it would otherwise take. Working on a national datasets or similarly large datasets w/o efficient code takes away all the improvements made possible by modern computing.

I had multiple a-ha moments while writing code. One major one in Lab 7 happened when I realized that I could create a custom ggplot function that used the argument input as both an input for a variable as well as the title to the plot (sup.artif: Lab 7, Task 5.1). Another a-ha moment was when I used a for loop to iteratively annotate a ggplot with the values from a column. Now, after seeing custom functions and the map() function I would probably write it differently, but at the time it was a breakthrough (sup.artif: Lab2Challenge, Task 1). A basic, but important a-ha moment was when I realized that functions like filter do not need to be piped and rewritten over and over again to to apply multiple filters. All that needs to be done is place a comma at the end of the initial filter and write out the new filter (sup.artif: Lab 3 Revised, Task: Filtering Bieber).
